In [1]:
import numpy as np

In [2]:
def get_random_mat(row, col, low = 0, high = 1):
    return np.random.uniform(low = low, high = high, size=(row,col))
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivative_sigmoid(x):
    return x * (1-x)

In [4]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])
input_mat_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1
wh = get_random_mat(input_mat_neurons,hidden_neurons)
bh = get_random_mat(1,hidden_neurons)
wout = get_random_mat(hidden_neurons,output_neurons)
bout = get_random_mat(1,output_neurons)
lr = 0.1
hidden_layer_input = np.dot(X,wh) + bh
hidden_layer_activation = sigmoid(hidden_layer_input)
output_layer = np.dot(hidden_layer_activation,wout) + bout
output = sigmoid(output_layer)
E = y - output

In [14]:
print('input_array : \n', X, '\n')
print('wh : \n', wh,'\n')
print ('bh : \n', bh,'\n')

print('hidden_layer_input : \n', hidden_layer_input, '\n')
print('Applying Sigmoid Function for Activation \n')
print('hidden_layer_activation : \n', hidden_layer_activation,'\n')
print ('wout : \n', wout,'\n')
print ('y : \n', y,'\n')
print ('Output : \n', output,'\n')
print ('Error : \n', E,'\n')

input_array : 
 [[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]] 

wh : 
 [[0.6582842  0.90189588 0.45114257]
 [0.39536887 0.24181187 0.30526004]
 [0.22469505 0.18508499 0.3378869 ]
 [0.89105716 0.46155404 0.17951312]] 

bh : 
 [[0.53840912 0.00462223 0.74613692]] 

hidden_layer_input : 
 [[1.42138836 1.0916031  1.5351664 ]
 [2.31244553 1.55315714 1.71467952]
 [1.82483515 0.70798813 1.23091009]] 

Applying Sigmoid Function for Activation 

hidden_layer_activation : 
 [[0.80555598 0.74868348 0.82276096]
 [0.90990254 0.82536925 0.84744225]
 [0.8611453  0.66995646 0.77397782]] 

wout : 
 [[0.96552967]
 [0.90683696]
 [0.10288495]] 

y : 
 [[1]
 [1]
 [0]] 

Output : 
 [[0.9201392 ]
 [0.93195216]
 [0.91845227]] 

Error : 
 [[ 0.0798608 ]
 [ 0.06804784]
 [-0.91845227]] 



In [15]:
slope_output = derivative_sigmoid(output)
delta_output = E * slope_output

print('Output Slope : \n', slope_output, '\n')
print('Delta Output : \n', delta_output,'\n')

Output Slope : 
 [[0.07348305]
 [0.06341734]
 [0.0748977 ]] 

Delta Output : 
 [[ 0.00586841]
 [ 0.00431541]
 [-0.06878996]] 



In [16]:
slope_hidden_layer = derivative_sigmoid(hidden_layer_activation)
error_at_hidden_layer = delta_output.dot(wout.T)
delta_hidden_layer = error_at_hidden_layer * slope_hidden_layer

print('Hidden Layer Slope : \n', slope_hidden_layer, '\n')
print('Error at hidden layer : \n', error_at_hidden_layer,'\n')
print('Delta at hidden layer: \n', delta_hidden_layer,'\n')

Hidden Layer Slope : 
 [[0.15663555 0.18815653 0.14582536]
 [0.08197991 0.14413485 0.12928388]
 [0.11957408 0.2211148  0.17493615]] 

Error at hidden layer : 
 [[ 0.00566613  0.0053217   0.00060377]
 [ 0.00416666  0.00391338  0.00044399]
 [-0.06641875 -0.06238128 -0.00707745]] 

Delta at hidden layer: 
 [[ 8.87517168e-04  1.00131177e-03  8.80452061e-05]
 [ 3.41582344e-04  5.64053865e-04  5.74008843e-05]
 [-7.94196060e-03 -1.37934246e-02 -1.23810217e-03]] 



In [19]:
wout += hidden_layer_activation.T.dot(delta_output) * lr
bout += np.sum(delta_output,axis = 0, keepdims=True) * lr
wh += X.T.dot(delta_hidden_layer) * lr
bh += np.sum(delta_hidden_layer, axis = 0, keepdims=True)* lr

print('Updated weights at output : \n', wout, '\n')
print('Updated bias at output : \n', bout,'\n')
print('Updated weights at input: \n', wh,'\n')
print('Updated bias at input : \n', bh,'\n')

Updated weights at output : 
 [[0.95541283]
 [0.89921079]
 [0.09393364]] 

Updated bias at output : 
 [[0.8911469]] 

Updated weights at input: 
 [[0.65840711 0.90205242 0.45115712]
 [0.39457467 0.24043252 0.30513623]
 [0.22481796 0.18524153 0.33790144]
 [0.89029713 0.4602311  0.17939505]] 

Updated bias at input : 
 [[0.53773783 0.00339942 0.74602766]] 

